### ISSUE TITLE
Тестовая задача

### ISSUE THREAD

**Issue by gsvgit** [YaccConstructor/Meerkat#3]
Реализовать на Scala библиотеку парсер-комбинаторов. Снабдить её тестами и примерами. Опубликовать на github. Ссылку на репозиторий оставлять в комментариях к этой таске. Вопросы задавать там же.

**Comment by loskutov** [comment]
https://github.com/loskutov/innovative-parser-combinators

**Comment by darthorimar** [comment]
https://github.com/darthorimar/tiny-parser-combinators

**Comment by maxkvant** [comment]
https://github.com/maxkvant/ScalaSimpleCombinatorParser

**Comment by fedochet** [comment]
https://github.com/fedochet/parser-combinators-library
